### ISSUE TITLE
[Improvement] Add back the objectdb updater

### ISSUE THREAD

**Issue by islender** [RealTheSunCat/Whitehole-1.4#11]
Since there's a new site for the db, the updater should be added back imo. Maybe an option that lets you toggle it on and off if the site goes down again?

btw, if it isn't know, this is where the new database is stored: http://shibboleet.us.to/database/objectdb.php

**Comment by IonicPixels** [comment]
Working on it

**Comment by IonicPixels** [comment]
The Objectdb Updater has now been reimplemented.
