### ISSUE TITLE
does not exist error

### ISSUE THREAD

**Issue by sup552** [RealTheSunCat/Whitehole-1.4#12]
watch video show the error in progress ~~~ https://www.youtube.com/watch?v=-vXKqtAHiBk

**Comment by TheSunCat** [comment]
hi, you need to download the latest release from [here](https://github.com/RealTheSunCat/Whitehole-1.4/releases) and open the **.jar file**. What you're doing in the video is trying to open the source code, which can't run as a program.

**Comment by sup552** [comment]
please help I can't seem figure out how to open Whitehole.class
this was the one not in the sorce code

**Comment by TheSunCat** [comment]
Hi! You need to install Java on your system, and use Java to run Whitehole.jar. You can find Java [here](https://www.java.com/download/).

If double-clicking the jar file does not work, you can click on the file path in Windows explorer and type this: `java -jar Whitehole.jar` to force it to open the jarfile with java.

Good luck! Feel free to contact me on Discord (TheSunCat#1007).
