### ISSUE TITLE
Group Translation and Rotation.

### ISSUE THREAD

**Issue by poudink** [RealTheSunCat/Whitehole-1.4#13]
the code is already done, you just need to add it http://kuribo64.net/board/thread.php?pid=99435#99435

**Comment by poudink** [comment]
the dude fixed multi object copy paste too, apparently. http://kuribo64.net/board/thread.php?pid=99440#99440
should I do a PR? I'm not the one making these code changes but it'd be nice if they were added here.

**Comment by TheSunCat** [comment]
yes please! I'd be happy to accept the PR if you can create it.

**Comment by TheSunCat** [comment]
I found wiiranbo's fork, merged it in now. Thanks!
