### ISSUE TITLE
STILL can't open any galaxies, and the game directory is already showing on startup

### ISSUE THREAD

**Issue by yourizuring** [RealTheSunCat/Whitehole-1.4#18]
I still can't open any galaxies, and the game directory is already opened on startup. I placed the object database inside the folder as well, thinking it'll work, but it still shows the game directory on startup, and I can NOT open any galaxies, still! No crash reports, no errors, nothing. How is the 'Open galaxy' button fixed then?

**Comment by IonicPixels** [comment]
Are you still having this problem? Whitehole has gotten several updates. Try with the newest version, and report back if you are still having this issue.

**Comment by Lenuto** [comment]
Using the latest version does not help.
Same issues here

**Comment by Lenuto** [comment]
Got help von a person, you need to have the newest jdk version

**Comment by IonicPixels** [comment]
@Lenuto ah ok, so its just a Java issue?

**Comment by IonicPixels** [comment]
also @yourizuring the game directory being open on startup is an option in the settings, meaning it intentional, and not an issue. If it really bothers you, disable that opttion
