### ISSUE TITLE
Inability to open galaxies on latest version.

### ISSUE THREAD

**Issue by gayfrogog** [RealTheSunCat/Whitehole-1.4#5]
Something y'all did broke the level editor portion of the level editor between now and the last time I used Whitehole. 
Galaxies straight up do not open. No crash dump, nothing.

**Comment by gayfrogog** [comment]
Just checked, the issue also extends to editing BCSV files in general.

**Comment by TheSunCat** [comment]
It seems to be fixed now thanks to https://github.com/RealTheSunCat/Whitehole-1.4/commit/81716dbae8c770c5ff9041d0feb99320e1aa90af

It was an issue related to Java being dumb and claiming a field doesn't exist. Let me know if it still happens, but it seems to have been squashed.
